# Generated by Django 3.2.9 on 2021-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.EmailField(default='correo@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
