# Generated by Django 3.2.9 on 2021-12-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contraseña',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
