# Generated by Django 3.2.9 on 2021-12-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
